language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
  - COMPOSER_OPTS=""
  - COMPOSER_OPTS="--prefer-lowest"

install:
  - composer self-update
  - composer update $COMPOSER_OPTS

before_script:
  - gem install --quiet mailcatcher
  - mailcatcher

script:
  - ./vendor/bin/phpunit
  - ./tests/lint.sh

git:
  depth: 5
