language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

install:
  - composer install

before_script:
  - gem install mailcatcher
  - mailcatcher --smtp-port 25

script:
  - phpunit tests
  - ./tests/lint.sh

git:
  depth: 5
