language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm
  - nightly

matrix:
  allow_failures:
  - php: nightly

env:
  - COMPOSER_OPTS=""
  - COMPOSER_OPTS="--prefer-lowest"

install:
  - composer self-update --snapshot
  - composer update $COMPOSER_OPTS

before_script:
  - gem install --quiet mailcatcher
  - mailcatcher

script:
  - ./vendor/bin/phpunit
  - ./tests/lint.sh

git:
  depth: 5
